# -*- coding: utf-8 -*-
"""gtfs_rt_supabase_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x68oIqDPz2IbEbsLCv-tpbAnNBliCEu5
"""

# -*- coding: utf-8 -*-
"""
GTFS-RT → Supabase Pipeline
============================
Fetches vehicle positions, service alerts, and trip updates from the OVapi
GTFS-RT feeds, parses each into a flat tabular DataFrame, and upserts the
rows into Supabase Postgres tables.

Requirements
------------
pip install protobuf requests gtfs-realtime-bindings \
            pandas numpy pyarrow supabase python-dotenv pytz

Environment variables (put in a .env file or set directly):
    SUPABASE_URL   – your Supabase project URL
    SUPABASE_KEY   – your Supabase service-role or anon key

Supabase table DDL is printed at the bottom of this file (run it once in the
Supabase SQL Editor before starting the pipeline).
"""

# ── stdlib ────────────────────────────────────────────────────────────────────
import os
import time
import math
import json
import logging
import re
from datetime import datetime, timedelta
from functools import lru_cache
from typing import Dict, List, Optional, Tuple

# ── third-party ───────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
import requests
from requests.exceptions import RequestException
from google.transit import gtfs_realtime_pb2
from supabase import create_client, Client
from dotenv import load_dotenv

# ── logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# 0.  CONFIGURATION


load_dotenv()  # reads .env if present

SUPABASE_URL: str = os.environ["SUPABASE_URL"]
SUPABASE_KEY: str = os.environ["SUPABASE_KEY"]

GTFS_RT_FEEDS: Dict[str, str] = {
    "vehicle_positions": "http://gtfs.ovapi.nl/nl/vehiclePositions.pb",
    "trip_updates":      "http://gtfs.ovapi.nl/nl/tripUpdates.pb",
    "alerts":            "http://gtfs.ovapi.nl/nl/alerts.pb",
}

# How often to poll (seconds). 15 minutes keeps you well within typical
# GTFS-RT update cadences while not hammering the server.
POLL_INTERVAL_SECONDS: int = 15 * 60

# How long to run in total (default: 7 days).
# Change to e.g. timedelta(days=30) for a month of data.
RUN_DURATION: timedelta = timedelta(days=7)

TIMEZONE: str = "Europe/Amsterdam"

# Supabase upsert batch size (rows per request)
BATCH_SIZE: int = 500



# 1.  UTILITY HELPERS


def ts_to_local(timestamp, timezone: str = TIMEZONE) -> Optional[str]:
    """Convert a Unix timestamp (int/float) to a local datetime string."""
    if timestamp is None or (isinstance(timestamp, float) and math.isnan(timestamp)):
        return None
    try:
        dt = pd.to_datetime(timestamp, unit="s", utc=True, errors="coerce")
        if pd.isna(dt):
            return None
        return dt.tz_convert(timezone).tz_localize(None).strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return None


def businessday_to_datetime(date: str, time_str: str) -> Optional[datetime]:
    """Parse GTFS service-date + extended time (hours ≥ 24 allowed)."""
    try:
        base = datetime.strptime(date, "%Y%m%d")
        h, m, s = map(int, time_str.split(":"))
        return base + timedelta(days=h // 24, hours=h % 24, minutes=m, seconds=s)
    except Exception:
        return None


def clean_text(text: str) -> str:
    """Lightweight text cleaner for alert descriptions."""
    if not text:
        return ""
    text = re.sub(r"<[^>]+>", " ", str(text))
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    text = re.sub(r"[^\w\sÀ-ÿ]", " ", text)
    return re.sub(r"\s+", " ", text).strip().lower()


def get_first_translation(field) -> Optional[str]:
    """Extract the first translation text from a GTFS-RT TranslatedString."""
    if field and hasattr(field, "translation") and len(field.translation) > 0:
        return field.translation[0].text
    return None


SCHEDULE_REL_MAP = {
    0: "SCHEDULED",
    1: "ADDED",
    2: "UNSCHEDULED",
    3: "CANCELED",
    5: "REPLACEMENT",
}

VEHICLE_STATUS_MAP = {
    0: "INCOMING_AT",
    1: "STOPPED_AT",
    2: "IN_TRANSIT_TO",
}



# 2.  FEED FETCHING


def fetch_feed(feed_name: str, url: str) -> Optional[gtfs_realtime_pb2.FeedMessage]:
    """Download and parse a single GTFS-RT protobuf feed."""
    try:
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        feed = gtfs_realtime_pb2.FeedMessage()
        feed.ParseFromString(resp.content)
        log.info("Fetched %s (%d entities)", feed_name, len(feed.entity))
        return feed
    except Exception as exc:
        log.error("Error fetching %s: %s", feed_name, exc)
        return None


def fetch_all_feeds() -> Dict[str, Optional[gtfs_realtime_pb2.FeedMessage]]:
    return {name: fetch_feed(name, url) for name, url in GTFS_RT_FEEDS.items()}



# 3.  PARSERS  →  flat DataFrames


# ── 3a. Vehicle Positions ─────────────────────────────────────────────────────

def parse_vehicle_positions(feed: gtfs_realtime_pb2.FeedMessage) -> pd.DataFrame:
    """
    Flatten a VehiclePositions FeedMessage into a DataFrame.

    Columns
    -------
    entity_id, trip_id, route_id, direction_id,
    start_time, start_date, trip_start_datetime,
    schedule_relationship_raw, schedule_relationship,
    vehicle_id, vehicle_label,
    latitude, longitude,
    current_stop_sequence, stop_id,
    current_status_raw, current_status,
    timestamp, occupancy_status,
    fetched_at
    """
    rows = []
    fetched_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

    for entity in feed.entity:
        if getattr(entity, "is_deleted", False):
            continue
        vehicle = getattr(entity, "vehicle", None)
        if vehicle is None:
            continue

        trip   = getattr(vehicle, "trip",     None)
        pos    = getattr(vehicle, "position", None)
        veh    = getattr(vehicle, "vehicle",  None)

        start_date = getattr(trip, "start_date", None) if trip else None
        start_time = getattr(trip, "start_time", None) if trip else None

        sched_raw = getattr(trip, "schedule_relationship", 0) if trip else 0

        rows.append({
            "entity_id":               getattr(entity, "id", None),
            "trip_id":                 getattr(trip, "trip_id",   None) if trip else None,
            "route_id":                getattr(trip, "route_id",  None) if trip else None,
            "direction_id":            getattr(trip, "direction_id", None) if trip else None,
            "start_time":              start_time,
            "start_date":              start_date,
            "trip_start_datetime":     businessday_to_datetime(start_date, start_time)
                                       if start_date and start_time else None,
            "schedule_relationship_raw": sched_raw,
            "schedule_relationship":   SCHEDULE_REL_MAP.get(sched_raw, "UNKNOWN"),
            "vehicle_id":              getattr(veh, "id",    None) if veh else None,
            "vehicle_label":           getattr(veh, "label", None) if veh else None,
            "latitude":                getattr(pos, "latitude",  None) if pos else None,
            "longitude":               getattr(pos, "longitude", None) if pos else None,
            "current_stop_sequence":   getattr(vehicle, "current_stop_sequence", None),
            "stop_id":                 getattr(vehicle, "stop_id", None),
            "current_status_raw":      getattr(vehicle, "current_status", 2),
            "current_status":          VEHICLE_STATUS_MAP.get(
                                           getattr(vehicle, "current_status", 2), "UNKNOWN"
                                       ),
            "timestamp":               ts_to_local(getattr(vehicle, "timestamp", None)),
            "occupancy_status":        getattr(vehicle, "occupancy_status", None),
            "fetched_at":              fetched_at,
        })

    df = pd.DataFrame(rows)
    if df.empty:
        return df

    # ── derived speed features ────────────────────────────────────────────────
    df["timestamp_dt"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df = df.sort_values(["vehicle_id", "timestamp_dt"])
    df["prev_lat"]  = df.groupby("vehicle_id")["latitude"].shift(1)
    df["prev_lon"]  = df.groupby("vehicle_id")["longitude"].shift(1)
    df["prev_time"] = df.groupby("vehicle_id")["timestamp_dt"].shift(1)
    df["distance_m"] = df.apply(_haversine_row, axis=1)
    df["time_diff_s"] = (df["timestamp_dt"] - df["prev_time"]).dt.total_seconds()
    df["speed_mps"]   = np.where(df["time_diff_s"] > 0,
                                 df["distance_m"] / df["time_diff_s"], 0)
    df["speed_kmph"]  = np.clip(df["speed_mps"] * 3.6, 0, 200)
    df["is_stationary"] = (df["speed_kmph"] < 1).astype(int)
    df.drop(columns=["timestamp_dt", "prev_lat", "prev_lon", "prev_time",
                     "distance_m", "time_diff_s", "speed_mps"], inplace=True)

    return df


def _haversine_row(row) -> float:
    if pd.isna(row["prev_lat"]):
        return 0.0
    R = 6_371_000
    lat1, lon1 = math.radians(row["prev_lat"]),  math.radians(row["prev_lon"])
    lat2, lon2 = math.radians(row["latitude"]),  math.radians(row["longitude"])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ── 3b. Service Alerts ────────────────────────────────────────────────────────

def parse_alerts(feed: gtfs_realtime_pb2.FeedMessage) -> pd.DataFrame:
    """
    Flatten a ServiceAlerts FeedMessage into a DataFrame.
    One row per (alert × informed_entity).

    Columns
    -------
    feed_timestamp, alert_id, cause_id, cause, effect_id, effect,
    header_text, description_text, url_text,
    active_period_start, active_period_end, alert_duration_min,
    informed_agency_id, informed_route_id, informed_route_type,
    informed_stop_id, informed_trip_id,
    clean_description, text_length, word_count,
    fetched_at
    """
    feed_ts    = ts_to_local(getattr(feed.header, "timestamp", None))
    fetched_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    rows = []

    for entity in feed.entity:
        if not entity.HasField("alert"):
            continue
        alert = entity.alert

        desc_text   = get_first_translation(getattr(alert, "description_text", None)) or ""
        header_text = get_first_translation(getattr(alert, "header_text",      None)) or ""

        # Active period
        ap_start = ap_end = None
        periods = getattr(alert, "active_period", [])
        if periods:
            ap_start = ts_to_local(periods[0].start) if periods[0].start else None
            ap_end   = ts_to_local(periods[0].end)   if periods[0].end   else None

        duration_min = None
        if ap_start and ap_end:
            try:
                fmt = "%Y-%m-%d %H:%M:%S"
                delta = datetime.strptime(ap_end, fmt) - datetime.strptime(ap_start, fmt)
                duration_min = delta.total_seconds() / 60
            except Exception:
                pass

        base = {
            "feed_timestamp":        feed_ts,
            "alert_id":              getattr(entity, "id", None),
            "cause_id":              alert.cause,
            "cause":                 gtfs_realtime_pb2.Alert.Cause.Name(alert.cause),
            "effect_id":             alert.effect,
            "effect":                gtfs_realtime_pb2.Alert.Effect.Name(alert.effect),
            "header_text":           header_text,
            "description_text":      desc_text,
            "url_text":              get_first_translation(getattr(alert, "url", None)),
            "active_period_start":   ap_start,
            "active_period_end":     ap_end,
            "alert_duration_min":    duration_min,
            "clean_description":     clean_text(desc_text),
            "text_length":           len(desc_text),
            "word_count":            len(desc_text.split()),
            "fetched_at":            fetched_at,
        }

        informed = list(getattr(alert, "informed_entity", []))
        if not informed:
            rows.append({**base,
                         "informed_agency_id": None, "informed_route_id": None,
                         "informed_route_type": None, "informed_stop_id": None,
                         "informed_trip_id": None})
        else:
            for ie in informed:
                trip_id = None
                if ie.HasField("trip"):
                    trip_id = getattr(ie.trip, "trip_id", None)
                rows.append({**base,
                             "informed_agency_id":   getattr(ie, "agency_id",   None),
                             "informed_route_id":    getattr(ie, "route_id",    None),
                             "informed_route_type":  getattr(ie, "route_type",  None),
                             "informed_stop_id":     getattr(ie, "stop_id",     None),
                             "informed_trip_id":     trip_id})

    return pd.DataFrame(rows)


# ── 3c. Trip Updates ──────────────────────────────────────────────────────────

def parse_trip_updates(feed: gtfs_realtime_pb2.FeedMessage) -> pd.DataFrame:
    """
    Flatten a TripUpdates FeedMessage into a DataFrame.
    One row per (trip_update × stop_time_update).

    Columns
    -------
    entity_id, trip_id, route_id, direction_id,
    start_time, start_date, trip_start_datetime,
    schedule_relationship_raw, schedule_relationship,
    vehicle_id,
    stop_sequence, stop_id,
    arrival_time, departure_time,
    arrival_delay_seconds, departure_delay_seconds,
    arrival_time_local, departure_time_local,
    delay, is_delayed, is_heavily_delayed,
    fetched_at
    """
    fetched_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    rows = []

    for entity in feed.entity:
        if not entity.HasField("trip_update"):
            continue
        tu   = entity.trip_update
        trip = tu.trip

        start_date = getattr(trip, "start_date", None)
        start_time = getattr(trip, "start_time", None)
        sched_raw  = getattr(trip, "schedule_relationship", 0)

        veh    = getattr(tu, "vehicle", None)
        veh_id = getattr(veh, "id", None) if veh else None

        base = {
            "entity_id":               getattr(entity, "id", None),
            "trip_id":                 getattr(trip, "trip_id",   None),
            "route_id":                getattr(trip, "route_id",  None),
            "direction_id":            getattr(trip, "direction_id", None),
            "start_time":              start_time,
            "start_date":              start_date,
            "trip_start_datetime":     businessday_to_datetime(start_date, start_time)
                                       if start_date and start_time else None,
            "schedule_relationship_raw": sched_raw,
            "schedule_relationship":   SCHEDULE_REL_MAP.get(sched_raw, "UNKNOWN"),
            "vehicle_id":              veh_id,
            "fetched_at":              fetched_at,
        }

        stu_list = list(getattr(tu, "stop_time_update", []))
        if not stu_list:
            rows.append({**base,
                         "stop_sequence": None, "stop_id": None,
                         "arrival_time": None,  "departure_time": None,
                         "arrival_delay_seconds": None, "departure_delay_seconds": None,
                         "arrival_time_local": None,    "departure_time_local": None,
                         "delay": 0, "is_delayed": 0,  "is_heavily_delayed": 0})
        else:
            for stu in stu_list:
                arr = getattr(stu, "arrival",   None)
                dep = getattr(stu, "departure", None)

                arr_time  = getattr(arr, "time",  None) if arr else None
                dep_time  = getattr(dep, "time",  None) if dep else None
                arr_delay = getattr(arr, "delay", 0)    if arr else 0
                dep_delay = getattr(dep, "delay", 0)    if dep else 0

                delay = max(arr_delay or 0, dep_delay or 0)

                rows.append({**base,
                             "stop_sequence":           getattr(stu, "stop_sequence", None),
                             "stop_id":                 getattr(stu, "stop_id",       None),
                             "arrival_time":            arr_time,
                             "departure_time":          dep_time,
                             "arrival_delay_seconds":   arr_delay,
                             "departure_delay_seconds": dep_delay,
                             "arrival_time_local":      ts_to_local(arr_time),
                             "departure_time_local":    ts_to_local(dep_time),
                             "delay":                   delay,
                             "is_delayed":              int(delay > 0),
                             "is_heavily_delayed":      int(delay >= 120)})

    df = pd.DataFrame(rows)
    return df



# 4.  SUPABASE  UPSERT HELPERS


def get_supabase_client() -> Client:
    return create_client(SUPABASE_URL, SUPABASE_KEY)


def _sanitize_for_json(obj):
    """Recursively make a value JSON-serialisable."""
    if obj is None:
        return None
    if isinstance(obj, float):
        if math.isnan(obj):
            return None
        # Convert whole-number floats (185.0) to int so Postgres INTEGER accepts them
        if obj == int(obj):
            return int(obj)
        return obj
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return None if math.isnan(float(obj)) else (
            int(float(obj)) if float(obj) == int(float(obj)) else float(obj)
        )
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, (pd.Timestamp, datetime)):
        return str(obj) if pd.notna(obj) else None
    if isinstance(obj, dict):
        return {k: _sanitize_for_json(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_sanitize_for_json(i) for i in obj]
    return obj


def df_to_records(df: pd.DataFrame) -> List[dict]:
    """Convert DataFrame to a list of JSON-safe dicts."""
    records = df.where(pd.notnull(df), None).to_dict(orient="records")
    return [_sanitize_for_json(r) for r in records]


def upsert_to_supabase(
    client: Client,
    table: str,
    df: pd.DataFrame,
    conflict_columns: List[str],
    batch_size: int = BATCH_SIZE,
) -> int:
    """
    Upsert a DataFrame into a Supabase table in batches.
    Returns total rows upserted.
    """
    if df.empty:
        log.info("  [%s] Nothing to upsert (empty DataFrame).", table)
        return 0

    records = df_to_records(df)
    total   = 0

    for i in range(0, len(records), batch_size):
        batch = records[i : i + batch_size]
        try:
            client.table(table).upsert(
                batch,
                on_conflict=",".join(conflict_columns)
            ).execute()
            total += len(batch)
            log.info("  [%s] Upserted rows %d–%d", table, i + 1, i + len(batch))
        except Exception as exc:
            log.error("  [%s] Upsert failed for batch %d: %s", table, i, exc)

    return total

def run_once():
    client = get_supabase_client()
    feeds  = fetch_all_feeds()

    if feeds.get("vehicle_positions"):
        vp_df = parse_vehicle_positions(feeds["vehicle_positions"])
        upsert_to_supabase(client, "vehicle_positions", vp_df,
                           conflict_columns=["entity_id", "timestamp"])

    if feeds.get("alerts"):
        al_df = parse_alerts(feeds["alerts"])
        upsert_to_supabase(client, "service_alerts", al_df,
                           conflict_columns=["alert_id", "feed_timestamp",
                                             "informed_route_id", "informed_stop_id"])

    if feeds.get("trip_updates"):
        tu_df = parse_trip_updates(feeds["trip_updates"])
        upsert_to_supabase(client, "trip_updates", tu_df,
                           conflict_columns=["entity_id", "stop_sequence",
                                             "arrival_time", "departure_time"])
    log.info("Single run complete.")

if __name__ == "__main__":
    run_once()
